# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '15.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'NEOED Technologies',
    'depends': [
        'sale_subscription',
        'product',
        'web_studio',
        'sale',
        'student_manager',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_menu.xml',
        'views/inherit_sale_subscription_view_form.xml',
        'views/inherit_product_template_for_view.xml',
        'views/inherit_res_partner_form_view.xml',
        'views/inherit_sale_subscription_view_list.xml',
        'views/inherit_sale_subscription_view_search.xml',
        'views/inherit_account_move_tree.xml',
        'views/inherit_account_move_search_view.xml',
        'views/inherit_account_move_form_view.xml',
        'views/inherit_sale_subscription_action_window.xml',
        'views/inherit_account_journal_form_view.xml',
        'views/billing_month_wizard.xml',
        'views/inherit_account_payment_tree_view.xml',
        'views/inherit_account_payment_form_view.xml',
        'views/inherit_res_partner_search_view.xml',
    ],

    'assets': {
        'web.assets_backend': [
            'fee_manager/static/src/js/payments.js',
        ],
    },
    'application': False,
    'license': 'OPL-1',
}
