from . import fkfp_photo_gallery
from . import fkfp_partner_document
from . import fields
from . import project_status
from . import inherit_res_company
from . import fkfp_donor
from . import vam
from . import smile
from . import micro_finance
from . import send_whatsapp_director_notification
from . import fkfp_staff
